apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-typescript-boilerplate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-typescript-boilerplate
  template:
    metadata:
      labels:
        app: react-typescript-boilerplate
    spec:
      containers:
        - name: app
          image: docker-registry.default.svc:5000/stefan-testing/react-app:1.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
